### ISSUE TITLE
my POM is not working, something is work with it 

### ISSUE THREAD

**Issue by Abhi1178singh** [Abhi1178singh/Auditauth#1]
Project build error: Non-resolvable parent POM: Failure to find org.springframework.boot:spring-boot-starter-parent:pom:1.1.3.RELEASE in http://repo.maven.apache.org/ maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM

**Comment by gayatrisingh31** [comment]
Hi @Abhi1178singh Can i resolve this issues?

**Comment by Abhi1178singh** [comment]
ya, sure it will be a great help.

**Comment by Abhi1178singh** [comment]
> Hi @Abhi1178singh Can i resolve this issues?

ya, sure it will be a great help.
